services:
  - type: web
    name: carnegienfreedom
    runtime: node
    buildCommand: npm install; npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: DB_SSL
        value: "true"
      - key: ALLOWED_ORIGINS
        sync: false
